jar:
	jar cvf data.jar \
           project \
           props \
           network.sif \
           commonNames.noa \
           pvalues.noa \
           dataSetCounts.noa \
           organismCount.noa \
           genes.noa \
           vizmap.props
	jarsigner -keystore jarkey -storepass honker data.jar  gaggle


